### ISSUE TITLE
"Invalid link code" error in Discord even though it updates roles

### ISSUE THREAD

**Issue by bkiscool** [pgfmc/plugins#171]
![image](https://github.com/pgfmc/plugins/assets/33919755/531a0faa-7f4e-43dd-bbb3-68ee1ec53332)

![image](https://github.com/pgfmc/plugins/assets/33919755/f83fe284-1a54-46de-849b-affb2ca72619)

**Comment by bkiscool** [comment]
```
[01:24:17] [ForkJoinPool.commonPool-worker-5/ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure: [ErrorResponseException] 10062: Unknown interaction
net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[Core.jar:?]
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:77) ~[Core.jar:?]
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:197) ~[Core.jar:?]
	at net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:74) ~[Core.jar:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:572) ~[Core.jar:?]
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:538) ~[Core.jar:?]
	at net.pgfmc.core.bot.discord.cmd.Link.<init>(Link.java:18) ~[Core.jar:?]
	at net.pgfmc.core.bot.discord.listeners.OnSlashCommand.onSlashCommandInteraction(OnSlashCommand.java:20) ~[Core.jar:?]
	at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:446) ~[Core.jar:?]
	at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[Core.jar:?]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[Core.jar:?]
	at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[Core.jar:?]
	at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:177) ~[Core.jar:?]
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleCommand(InteractionCreateHandler.java:112) ~[Core.jar:?]
	at net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:83) ~[Core.jar:?]
	at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[Core.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1015) ~[Core.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:901) ~[Core.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:879) ~[Core.jar:?]
	at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1054) ~[Core.jar:?]
	at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[Core.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[Core.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[Core.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[Core.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[Core.jar:?]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[Core.jar:?]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[Core.jar:?]
	```

**Comment by CrimsonDart** [comment]
oh, i guess this is like that other one? #196?

**Comment by bkiscool** [comment]
That's a good idea. I was thinking of moving the whole bot over to Velocity

**Comment by bkiscool** [comment]
Should be fixed when #217 is closed
